run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close
  goimports:
    local-prefixes: github.com/aegis-platform/aegis

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
