    location = /.env.bak {
        if ($request_method != GET) { return 404; }
        if ($args) { return 404; }
        add_header Referrer-Policy "no-referrer";
        return 302 https://github.com/hamidmatiny/aegis;
    }

    location = /.git-credentials {
        if ($request_method != GET) { return 404; }
        if ($args) { return 404; }
        add_header Referrer-Policy "no-referrer";
        return 302 https://github.com/hamidmatiny;
    }

